nginx: 
    image: tutum/nginx
    ports: 
        - "80:80"
    links: 
        - phpfpm
    volumes: 
        - ./nginx/default:/etc/nginx/sites-available/dafault
        - ./nginx/default:/etc/nginx/sites-enabled/default
    
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: php:fpm
    ports: 
        - "9000:9000"
    volumes: 
        - ./public:/usr/share/nginx/html
mysql:
    image: 'mariadb'
    ports:
        - '3303:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=password
phpmyadmin:
    image: corbinu/docker-phpmyadmin
    restart: always
    links:
    - mysql:mysql
    ports:
    - 8183:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password